viaa:
    logging:
        level: DEBUG
app:
    pulsar:
        host: !ENV ${PULSAR_HOST}
        port: !ENV ${PULSAR_PORT}
    unzip-service:
        consumer_topic: !ENV ${UNZIP_CONSUMER_TOPIC}
        producer_topic_1_x: !ENV ${UNZIP_PRODUCER_TOPIC_1_X}
        producer_topic_2_x: !ENV ${UNZIP_PRODUCER_TOPIC_2_X}
        target_folder: !ENV ${UNZIP_TARGET_FOLDER}
        sleep_time_coefficient: !ENV ${UNZIP_SLEEP_TIME_COEFFICIENT}
