viaa:
    logging:
        level: DEBUG
app:
    pulsar:
        host: !ENV ${PULSAR_HOST}
        port: !ENV ${PULSAR_PORT}
    unzip-service:
        consumer_topic: !ENV ${UNZIP_CONSUMER_TOPIC}
        producer_topic: !ENV ${UNZIP_PRODUCER_TOPIC}
        target_folder: !ENV ${UNZIP_TARGET_FOLDER}
